/* Nombre  Ratio  Imagen ValorExtra RatioEX */
const pokeballs = [
    ['PokeBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Poké-Ball.png', 'N', 1, 'POKE'],
    ['SuperBall', 1.5, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Super-Ball.png', 'N', 1, 'SUPER'],
    ['UltraBall', 2, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Ultra-Ball.png', 'N', 1, 'ULTRA'],
    ['MasterBall', 100, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Master-Ball.png', 'N', 1, 'MASTER'],
    ['MallaBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Malla-Ball.png', 'Si el Pokémon es agua o bicho', 3.5, 'MALLA'],
    ['NidoBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Nido-Ball.png', 'Si el nivel del Pokémon es menor de 30 la captura es máx de', 4, 'NIDO'],
    ['BuceoBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Buceo-Ball.png', 'Si el Pokémon está sobre o bajo el agua', 3.5, 'BUCEO'],
    ['AcopioBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Acopio-Ball.png', 'Si el Pokémon está registrado como capturado en la Pokédex', 3.5, 'ACOPIO'],
    ['TurnoBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Turno-Ball.png', 'Si el combate supera el turno 29', 4, 'TURNO'],
    ['VelozBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Veloz-Ball.png', 'Si es el primer turno de combate', 5, 'VELOZ'],
    ['OcasoBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Ocaso-Ball.png', 'Si el Pokémon está en una cueva o es de noche', 3, 'OCAS'],
    ['RapidBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Rapid-Ball.png', 'Si la velocidad base del Pokémon es 100 o más', 4, 'RAPID'],
    ['NivelBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Nivel-Ball.png', 'Si el nivel del Pokémon es 4 veces menor al del propio Pokémon', 8, 'NIVEL'],
    ['AmorBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Amor-Ball.png', 'Si el Pokémon es de género opuesto y misma especie que el tuyo', 8, 'AMOR'],
    ['CeboBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Cebo-Ball.png', 'Pescando', 5, 'CEBO'],
    ['LunaBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Luna-Ball-1.png', 'Si el Pokémon pertenece a la familia de Pokémon a una que evoluciona con piedra lunar', 4, 'LUNA'],
    ['HonorBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Honor-Ball.png', 'N', 1, 'HONOR'],
    ['LujoBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Lujo-Ball.png', 'N', 1, 'LUJO'],
    ['SanaBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Sana-Ball.png', 'N', 1, 'SANA'],
    ['GloriaBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Gloria-Ball.png', 'N', 1, 'GLORI'],
    ['EnsueñoBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Ensueño-Ball.png', 'N', 1, 'ENSU'],
    ['SafariBall', 1.5, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Safari-Ball.png', 'N', 1, 'SAFA'],
    ['PesoBall', 1, 'https://pokemonalpha.xyz/wp-content/uploads/2016/06/Peso-Ball.png', 'Si el Pokémon pesa más de 300 kg', 5, 'PESO'],
    ['EnteBall', 0.1, 'https://pokemonalpha.xyz/wp-content/uploads/Ente-Ball.png', 'Si se trata de un Ultraente', 5, 'ENTE']
]